### ISSUE TITLE
respiration to-do

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/mineral_om_incub#4]
- [x] APS will send ambient CO2 for flux calculation
- [x] normalize initial and final fluxes to total C 
- [x] cumulative fluxes/evolution: can be simply added
- [x] stats on cumulative CO2 evolved
